[main]
dst_emails = ""
email_watchlist = ""
vt_api_key = ""
blacklist = ""
whitelist = ""
domain_blacklist = ""
domain_whitelist = ""
mailer_mode = "gmail"
mailer_address = ""
mailer_pwd = ""
allow_tor = "false"